// AUTO-GENERATED by scripts/generate-location-inventory.mjs — do not edit by hand.
// Vehicle photos sourced from Pexels (https://pexels.com).

export const VEHICLE_IMAGES: Record<string, string[]> = {
  "1": [
    "/vehicles/1-1.webp",
    "/vehicles/1-2.webp"
  ],
  "2": [
    "/vehicles/2-1.webp",
    "/vehicles/2-2.webp"
  ],
  "3": [
    "/vehicles/3-1.webp",
    "/vehicles/3-2.webp"
  ],
  "4": [
    "/vehicles/1-1.webp",
    "/vehicles/1-2.webp"
  ],
  "5": [
    "/vehicles/5-1.webp",
    "/vehicles/5-2.webp"
  ],
  "6": [
    "/vehicles/6-1.webp",
    "/vehicles/6-2.webp"
  ],
  "7": [
    "/vehicles/7-1.webp",
    "/vehicles/7-2.webp"
  ],
  "8": [
    "/vehicles/8-1.webp",
    "/vehicles/8-2.webp"
  ],
  "9": [
    "/vehicles/9-1.webp",
    "/vehicles/9-2.webp"
  ],
  "10": [
    "/vehicles/10-1.webp",
    "/vehicles/10-2.webp"
  ],
  "11": [
    "/vehicles/11-1.webp",
    "/vehicles/11-2.webp"
  ],
  "12": [
    "/vehicles/12-1.webp",
    "/vehicles/12-2.webp"
  ],
  "13": [
    "/vehicles/12-1.webp",
    "/vehicles/12-2.webp"
  ],
  "14": [
    "/vehicles/5-1.webp",
    "/vehicles/5-2.webp"
  ],
  "15": [
    "/vehicles/5-1.webp",
    "/vehicles/5-2.webp"
  ],
  "16": [
    "/vehicles/6-1.webp",
    "/vehicles/6-2.webp"
  ],
  "17": [
    "/vehicles/8-1.webp",
    "/vehicles/8-2.webp"
  ],
  "18": [
    "/vehicles/18-1.webp",
    "/vehicles/18-2.webp"
  ],
  "19": [
    "/vehicles/19-1.webp",
    "/vehicles/19-2.webp"
  ],
  "20": [
    "/vehicles/3-1.webp",
    "/vehicles/3-2.webp"
  ],
  "21": [
    "/vehicles/11-1.webp",
    "/vehicles/11-2.webp"
  ],
  "22": [
    "/vehicles/12-1.webp",
    "/vehicles/12-2.webp"
  ],
  "23": [
    "/vehicles/18-1.webp",
    "/vehicles/18-2.webp"
  ],
  "24": [
    "/vehicles/9-1.webp",
    "/vehicles/9-2.webp"
  ],
  "25": [
    "/vehicles/3-1.webp",
    "/vehicles/3-2.webp"
  ],
  "26": [
    "/vehicles/1-1.webp",
    "/vehicles/1-2.webp"
  ],
  "27": [
    "/vehicles/7-1.webp",
    "/vehicles/7-2.webp"
  ],
  "28": [
    "/vehicles/8-1.webp",
    "/vehicles/8-2.webp"
  ],
  "29": [
    "/vehicles/8-1.webp",
    "/vehicles/8-2.webp"
  ],
  "30": [
    "/vehicles/18-1.webp",
    "/vehicles/18-2.webp"
  ],
  "31": [
    "/vehicles/5-1.webp",
    "/vehicles/5-2.webp"
  ],
  "32": [
    "/vehicles/6-1.webp",
    "/vehicles/6-2.webp"
  ],
  "33": [
    "/vehicles/7-1.webp",
    "/vehicles/7-2.webp"
  ],
  "34": [
    "/vehicles/8-1.webp",
    "/vehicles/8-2.webp"
  ],
  "35": [
    "/vehicles/12-1.webp",
    "/vehicles/12-2.webp"
  ],
  "36": [
    "/vehicles/5-1.webp",
    "/vehicles/5-2.webp"
  ],
  "37": [
    "/vehicles/37-1.webp",
    "/vehicles/37-2.webp"
  ],
  "38": [
    "/vehicles/11-1.webp",
    "/vehicles/11-2.webp"
  ],
  "39": [
    "/vehicles/11-1.webp",
    "/vehicles/11-2.webp"
  ],
  "40": [
    "/vehicles/12-1.webp",
    "/vehicles/12-2.webp"
  ],
  "41": [
    "/vehicles/11-1.webp",
    "/vehicles/11-2.webp"
  ],
  "42": [
    "/vehicles/12-1.webp",
    "/vehicles/12-2.webp"
  ],
  "43": [
    "/vehicles/1-1.webp",
    "/vehicles/1-2.webp"
  ],
  "44": [
    "/vehicles/2-1.webp",
    "/vehicles/2-2.webp"
  ],
  "45": [
    "/vehicles/1-1.webp",
    "/vehicles/1-2.webp"
  ],
  "46": [
    "/vehicles/2-1.webp",
    "/vehicles/2-2.webp"
  ],
  "47": [
    "/vehicles/12-1.webp",
    "/vehicles/12-2.webp"
  ],
  "48": [
    "/vehicles/5-1.webp",
    "/vehicles/5-2.webp"
  ],
  "49": [
    "/vehicles/10-1.webp",
    "/vehicles/10-2.webp"
  ],
  "50": [
    "/vehicles/7-1.webp",
    "/vehicles/7-2.webp"
  ],
  "51": [
    "/vehicles/2-1.webp",
    "/vehicles/2-2.webp"
  ],
  "52": [
    "/vehicles/52-1.webp",
    "/vehicles/52-2.webp"
  ],
  "53": [
    "/vehicles/8-1.webp",
    "/vehicles/8-2.webp"
  ],
  "54": [
    "/vehicles/18-1.webp",
    "/vehicles/18-2.webp"
  ],
  "55": [
    "/vehicles/10-1.webp",
    "/vehicles/10-2.webp"
  ],
  "56": [
    "/vehicles/7-1.webp",
    "/vehicles/7-2.webp"
  ],
  "57": [
    "/vehicles/37-1.webp",
    "/vehicles/37-2.webp"
  ],
  "58": [
    "/vehicles/11-1.webp",
    "/vehicles/11-2.webp"
  ],
  "59": [
    "/vehicles/9-1.webp",
    "/vehicles/9-2.webp"
  ],
  "60": [
    "/vehicles/10-1.webp",
    "/vehicles/10-2.webp"
  ],
  "61": [
    "/vehicles/9-1.webp",
    "/vehicles/9-2.webp"
  ],
  "62": [
    "/vehicles/10-1.webp",
    "/vehicles/10-2.webp"
  ],
  "63": [
    "/vehicles/19-1.webp",
    "/vehicles/19-2.webp"
  ],
  "64": [
    "/vehicles/3-1.webp",
    "/vehicles/3-2.webp"
  ],
  "65": [
    "/vehicles/3-1.webp",
    "/vehicles/3-2.webp"
  ],
  "66": [
    "/vehicles/1-1.webp",
    "/vehicles/1-2.webp"
  ],
  "67": [
    "/vehicles/9-1.webp",
    "/vehicles/9-2.webp"
  ],
  "68": [
    "/vehicles/10-1.webp",
    "/vehicles/10-2.webp"
  ],
  "69": [
    "/vehicles/3-1.webp",
    "/vehicles/3-2.webp"
  ],
  "70": [
    "/vehicles/1-1.webp",
    "/vehicles/1-2.webp"
  ],
  "71": [
    "/vehicles/11-1.webp",
    "/vehicles/11-2.webp"
  ],
  "72": [
    "/vehicles/12-1.webp",
    "/vehicles/12-2.webp"
  ],
  "73": [
    "/vehicles/12-1.webp",
    "/vehicles/12-2.webp"
  ],
  "74": [
    "/vehicles/5-1.webp",
    "/vehicles/5-2.webp"
  ],
  "75": [
    "/vehicles/37-1.webp",
    "/vehicles/37-2.webp"
  ],
  "76": [
    "/vehicles/11-1.webp",
    "/vehicles/11-2.webp"
  ],
  "77": [
    "/vehicles/12-1.webp",
    "/vehicles/12-2.webp"
  ],
  "78": [
    "/vehicles/5-1.webp",
    "/vehicles/5-2.webp"
  ],
  "79": [
    "/vehicles/6-1.webp",
    "/vehicles/6-2.webp"
  ],
  "80": [
    "/vehicles/37-1.webp",
    "/vehicles/37-2.webp"
  ],
  "81": [
    "/vehicles/3-1.webp",
    "/vehicles/3-2.webp"
  ],
  "82": [
    "/vehicles/1-1.webp",
    "/vehicles/1-2.webp"
  ],
  "83": [
    "/vehicles/52-1.webp",
    "/vehicles/52-2.webp"
  ],
  "84": [
    "/vehicles/19-1.webp",
    "/vehicles/19-2.webp"
  ],
  "85": [
    "/vehicles/7-1.webp",
    "/vehicles/7-2.webp"
  ],
  "86": [
    "/vehicles/8-1.webp",
    "/vehicles/8-2.webp"
  ],
  "87": [
    "/vehicles/1-1.webp",
    "/vehicles/1-2.webp"
  ],
  "88": [
    "/vehicles/2-1.webp",
    "/vehicles/2-2.webp"
  ],
  "89": [
    "/vehicles/10-1.webp",
    "/vehicles/10-2.webp"
  ],
  "90": [
    "/vehicles/7-1.webp",
    "/vehicles/7-2.webp"
  ],
  "91": [
    "/vehicles/1-1.webp",
    "/vehicles/1-2.webp"
  ],
  "92": [
    "/vehicles/2-1.webp",
    "/vehicles/2-2.webp"
  ],
  "93": [
    "/vehicles/8-1.webp",
    "/vehicles/8-2.webp"
  ],
  "94": [
    "/vehicles/18-1.webp",
    "/vehicles/18-2.webp"
  ],
  "95": [
    "/vehicles/5-1.webp",
    "/vehicles/5-2.webp"
  ],
  "96": [
    "/vehicles/6-1.webp",
    "/vehicles/6-2.webp"
  ],
  "97": [
    "/vehicles/7-1.webp",
    "/vehicles/7-2.webp"
  ],
  "98": [
    "/vehicles/8-1.webp",
    "/vehicles/8-2.webp"
  ],
  "99": [
    "/vehicles/11-1.webp",
    "/vehicles/11-2.webp"
  ],
  "100": [
    "/vehicles/12-1.webp",
    "/vehicles/12-2.webp"
  ],
  "101": [
    "/vehicles/9-1.webp",
    "/vehicles/9-2.webp"
  ],
  "102": [
    "/vehicles/10-1.webp",
    "/vehicles/10-2.webp"
  ],
  "103": [
    "/vehicles/18-1.webp",
    "/vehicles/18-2.webp"
  ],
  "104": [
    "/vehicles/9-1.webp",
    "/vehicles/9-2.webp"
  ],
  "105": [
    "/vehicles/19-1.webp",
    "/vehicles/19-2.webp"
  ],
  "106": [
    "/vehicles/3-1.webp",
    "/vehicles/3-2.webp"
  ],
  "107": [
    "/vehicles/52-1.webp",
    "/vehicles/52-2.webp"
  ],
  "108": [
    "/vehicles/19-1.webp",
    "/vehicles/19-2.webp"
  ],
  "109": [
    "/vehicles/5-1.webp",
    "/vehicles/5-2.webp"
  ],
  "110": [
    "/vehicles/6-1.webp",
    "/vehicles/6-2.webp"
  ],
  "111": [
    "/vehicles/10-1.webp",
    "/vehicles/10-2.webp"
  ],
  "112": [
    "/vehicles/7-1.webp",
    "/vehicles/7-2.webp"
  ],
  "113": [
    "/vehicles/10-1.webp",
    "/vehicles/10-2.webp"
  ],
  "114": [
    "/vehicles/7-1.webp",
    "/vehicles/7-2.webp"
  ],
  "115": [
    "/vehicles/2-1.webp",
    "/vehicles/2-2.webp"
  ],
  "116": [
    "/vehicles/52-1.webp",
    "/vehicles/52-2.webp"
  ],
  "117": [
    "/vehicles/37-1.webp",
    "/vehicles/37-2.webp"
  ],
  "118": [
    "/vehicles/11-1.webp",
    "/vehicles/11-2.webp"
  ],
  "119": [
    "/vehicles/9-1.webp",
    "/vehicles/9-2.webp"
  ],
  "120": [
    "/vehicles/10-1.webp",
    "/vehicles/10-2.webp"
  ],
  "121": [
    "/vehicles/3-1.webp",
    "/vehicles/3-2.webp"
  ],
  "122": [
    "/vehicles/1-1.webp",
    "/vehicles/1-2.webp"
  ],
  "123": [
    "/vehicles/6-1.webp",
    "/vehicles/6-2.webp"
  ],
  "124": [
    "/vehicles/37-1.webp",
    "/vehicles/37-2.webp"
  ],
  "125": [
    "/vehicles/9-1.webp",
    "/vehicles/9-2.webp"
  ],
  "126": [
    "/vehicles/10-1.webp",
    "/vehicles/10-2.webp"
  ],
  "127": [
    "/vehicles/11-1.webp",
    "/vehicles/11-2.webp"
  ],
  "128": [
    "/vehicles/12-1.webp",
    "/vehicles/12-2.webp"
  ],
  "129": [
    "/vehicles/18-1.webp",
    "/vehicles/18-2.webp"
  ],
  "130": [
    "/vehicles/9-1.webp",
    "/vehicles/9-2.webp"
  ],
  "131": [
    "/vehicles/8-1.webp",
    "/vehicles/8-2.webp"
  ],
  "132": [
    "/vehicles/18-1.webp",
    "/vehicles/18-2.webp"
  ],
  "133": [
    "/vehicles/18-1.webp",
    "/vehicles/18-2.webp"
  ],
  "134": [
    "/vehicles/9-1.webp",
    "/vehicles/9-2.webp"
  ],
  "135": [
    "/vehicles/3-1.webp",
    "/vehicles/3-2.webp"
  ],
  "136": [
    "/vehicles/1-1.webp",
    "/vehicles/1-2.webp"
  ],
  "137": [
    "/vehicles/1-1.webp",
    "/vehicles/1-2.webp"
  ],
  "138": [
    "/vehicles/2-1.webp",
    "/vehicles/2-2.webp"
  ],
  "139": [
    "/vehicles/2-1.webp",
    "/vehicles/2-2.webp"
  ],
  "140": [
    "/vehicles/52-1.webp",
    "/vehicles/52-2.webp"
  ],
  "141": [
    "/vehicles/12-1.webp",
    "/vehicles/12-2.webp"
  ],
  "142": [
    "/vehicles/5-1.webp",
    "/vehicles/5-2.webp"
  ],
  "143": [
    "/vehicles/5-1.webp",
    "/vehicles/5-2.webp"
  ],
  "144": [
    "/vehicles/6-1.webp",
    "/vehicles/6-2.webp"
  ],
  "145": [
    "/vehicles/7-1.webp",
    "/vehicles/7-2.webp"
  ],
  "146": [
    "/vehicles/8-1.webp",
    "/vehicles/8-2.webp"
  ],
  "147": [
    "/vehicles/37-1.webp",
    "/vehicles/37-2.webp"
  ],
  "148": [
    "/vehicles/11-1.webp",
    "/vehicles/11-2.webp"
  ],
  "149": [
    "/vehicles/12-1.webp",
    "/vehicles/12-2.webp"
  ],
  "150": [
    "/vehicles/5-1.webp",
    "/vehicles/5-2.webp"
  ],
  "151": [
    "/vehicles/7-1.webp",
    "/vehicles/7-2.webp"
  ],
  "152": [
    "/vehicles/8-1.webp",
    "/vehicles/8-2.webp"
  ]
};
