// AUTO-GENERATED by scripts/fetch-car-images.mjs — do not edit by hand.
// Real vehicle photos sourced from Pexels (https://pexels.com).

export const VEHICLE_IMAGES: Record<string, string[]> = {
  "1": [
    "/vehicles/1-1.jpg",
    "/vehicles/1-2.jpg",
    "/vehicles/1-3.jpg",
    "/vehicles/1-4.jpg"
  ],
  "2": [
    "/vehicles/2-1.jpg",
    "/vehicles/2-2.jpg",
    "/vehicles/2-3.jpg",
    "/vehicles/2-4.jpg"
  ],
  "3": [
    "/vehicles/3-1.jpg",
    "/vehicles/3-2.jpg",
    "/vehicles/3-3.jpg",
    "/vehicles/3-4.jpg"
  ],
  "4": [
    "/vehicles/4-1.jpg",
    "/vehicles/4-2.jpg",
    "/vehicles/4-3.jpg",
    "/vehicles/4-4.jpg"
  ],
  "5": [
    "/vehicles/5-1.jpg",
    "/vehicles/5-2.jpg",
    "/vehicles/5-3.jpg",
    "/vehicles/5-4.jpg"
  ],
  "6": [
    "/vehicles/6-1.jpg",
    "/vehicles/6-2.jpg",
    "/vehicles/6-3.jpg",
    "/vehicles/6-4.jpg"
  ],
  "7": [
    "/vehicles/7-1.jpg",
    "/vehicles/7-2.jpg",
    "/vehicles/7-3.jpg",
    "/vehicles/7-4.jpg"
  ],
  "8": [
    "/vehicles/8-1.jpg",
    "/vehicles/8-2.jpg",
    "/vehicles/8-3.jpg",
    "/vehicles/8-4.jpg"
  ],
  "9": [
    "/vehicles/9-1.jpg",
    "/vehicles/9-2.jpg",
    "/vehicles/9-3.jpg",
    "/vehicles/9-4.jpg"
  ],
  "10": [
    "/vehicles/10-1.jpg",
    "/vehicles/10-2.jpg",
    "/vehicles/10-3.jpg",
    "/vehicles/10-4.jpg"
  ],
  "11": [
    "/vehicles/11-1.jpg",
    "/vehicles/11-2.jpg",
    "/vehicles/11-3.jpg",
    "/vehicles/11-4.jpg"
  ],
  "12": [
    "/vehicles/12-1.jpg",
    "/vehicles/12-2.jpg",
    "/vehicles/12-3.jpg",
    "/vehicles/12-4.jpg"
  ],
  "13": [
    "/vehicles/13-1.jpg",
    "/vehicles/13-2.jpg",
    "/vehicles/13-3.jpg",
    "/vehicles/13-4.jpg"
  ],
  "14": [
    "/vehicles/14-1.jpg",
    "/vehicles/14-2.jpg",
    "/vehicles/14-3.jpg",
    "/vehicles/14-4.jpg"
  ],
  "15": [
    "/vehicles/15-1.jpg",
    "/vehicles/15-2.jpg",
    "/vehicles/15-3.jpg",
    "/vehicles/15-4.jpg"
  ],
  "16": [
    "/vehicles/16-1.jpg",
    "/vehicles/16-2.jpg",
    "/vehicles/16-3.jpg",
    "/vehicles/16-4.jpg"
  ],
  "17": [
    "/vehicles/17-1.jpg",
    "/vehicles/17-2.jpg",
    "/vehicles/17-3.jpg",
    "/vehicles/17-4.jpg"
  ],
  "18": [
    "/vehicles/18-1.jpg",
    "/vehicles/18-2.jpg",
    "/vehicles/18-3.jpg",
    "/vehicles/18-4.jpg"
  ],
  "19": [
    "/vehicles/19-1.jpg",
    "/vehicles/19-2.jpg",
    "/vehicles/19-3.jpg",
    "/vehicles/19-4.jpg"
  ],
  "20": [
    "/vehicles/20-1.jpg",
    "/vehicles/20-2.jpg",
    "/vehicles/20-3.jpg",
    "/vehicles/20-4.jpg"
  ],
  "21": [
    "/vehicles/21-1.jpg",
    "/vehicles/21-2.jpg",
    "/vehicles/21-3.jpg",
    "/vehicles/21-4.jpg"
  ],
  "22": [
    "/vehicles/22-1.jpg",
    "/vehicles/22-2.jpg",
    "/vehicles/22-3.jpg",
    "/vehicles/22-4.jpg"
  ],
  "23": [
    "/vehicles/23-1.jpg",
    "/vehicles/23-2.jpg",
    "/vehicles/23-3.jpg",
    "/vehicles/23-4.jpg"
  ],
  "24": [
    "/vehicles/24-1.jpg",
    "/vehicles/24-2.jpg",
    "/vehicles/24-3.jpg",
    "/vehicles/24-4.jpg"
  ]
};
