// AUTO-GENERATED by scripts/fetch-blog-images.mjs — do not edit by hand.
// Cover images sourced from Pexels (https://pexels.com).

export const BLOG_IMAGES: Record<string, string> = {
  "new-vs-used-vs-cpo": "/blog/new-vs-used-vs-cpo.jpg",
  "reading-combined-ratings": "/blog/reading-combined-ratings.jpg",
  "best-suvs-under-30k": "/blog/best-suvs-under-30k.jpg",
  "financing-101": "/blog/financing-101.jpg",
  "electric-cars-guide": "/blog/electric-cars-guide.jpg",
  "test-drive-questions": "/blog/test-drive-questions.jpg",
  "inspect-used-car": "/blog/inspect-used-car.jpg",
  "trade-in-tips": "/blog/trade-in-tips.jpg",
  "best-family-road-trip-cars": "/blog/best-family-road-trip-cars.jpg",
  "winter-driving-prep": "/blog/winter-driving-prep.jpg",
  "understanding-carfax": "/blog/understanding-carfax.jpg",
  "cpo-explained": "/blog/cpo-explained.jpg"
};
