// AUTO-GENERATED by scripts/fetch-blog-images.mjs, do not edit by hand.
// Cover images sourced from Pexels (https://pexels.com).

export const BLOG_IMAGES: Record<string, string> = {
  "new-vs-used-vs-cpo": "/blog/new-vs-used-vs-cpo.webp",
  "reading-combined-ratings": "/blog/reading-combined-ratings.webp",
  "best-suvs-under-30k": "/blog/best-suvs-under-30k.webp",
  "financing-101": "/blog/financing-101.webp",
  "electric-cars-guide": "/blog/electric-cars-guide.webp",
  "test-drive-questions": "/blog/test-drive-questions.webp",
  "inspect-used-car": "/blog/inspect-used-car.webp",
  "trade-in-tips": "/blog/trade-in-tips.webp",
  "best-family-road-trip-cars": "/blog/best-family-road-trip-cars.webp",
  "winter-driving-prep": "/blog/winter-driving-prep.webp",
  "understanding-carfax": "/blog/understanding-carfax.webp",
  "cpo-explained": "/blog/cpo-explained.webp"
};
